# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-09-27 04:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('potluck', '0002_auto_20190924_2142'),
    ]

    operations = [
        migrations.AddField(
            model_name='potluckitem',
            name='raffle_participation',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='potluckitem',
            name='potluckItem_text',
            field=models.CharField(blank=True, default='I.E. Canopy or 2x Dog Collar(s)', max_length=200),
        ),
    ]
