# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-10-03 04:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('potluck', '0003_auto_20190926_2116'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='choice',
            name='question',
        ),
        migrations.AddField(
            model_name='potluckitem',
            name='instagram_account',
            field=models.CharField(default='', max_length=20),
        ),
        migrations.DeleteModel(
            name='Choice',
        ),
        migrations.DeleteModel(
            name='Question',
        ),
    ]
